const articles = [
  { number:"01", category:"Fundamentos", title:"¿Qué es un puro?", lead:"Tres partes, una sola experiencia: capa, capote y tripa.", body:"La capa es la hoja exterior y aporta apariencia y una parte decisiva del carácter. El capote sostiene la mezcla y favorece la combustión. La tripa reúne hojas seleccionadas para construir fortaleza, aroma y complejidad.", tags:["Anatomía","Capa","Mezcla"] },
  { number:"02", category:"Del campo al taller", title:"El viaje de la hoja", lead:"La paciencia empieza mucho antes de que una pieza llegue a la mesa de rolado.", body:"Germinación, cultivo, cosecha, secado, humectación, fermentación, selección y añejamiento transforman una hoja agrícola en materia prima para un puro equilibrado. El clima y cada variación de la hoja forman parte de la mezcla.", tags:["Origen","Fermentación","Añejamiento"] },
  { number:"03", category:"El oficio", title:"Cómo nace un Perro Negro", lead:"Torcer, armar y envolver: precisión que se reconoce en el tiro y la combustión.", body:"Las maestras enrolladoras distribuyen las hojas, forman el bonche, aplican el capote y envuelven la pieza con la capa. La uniformidad, el tacto y el acabado revelan la experiencia detrás de cada puro.", tags:["Hecho a mano","Construcción","Ecuador"] },
  { number:"04", category:"Guía de fumada", title:"Cortar y encender sin prisa", lead:"Un buen comienzo protege la estructura y permite una combustión pareja.", body:"El corte debe abrir el tiro sin atravesar de más la perilla. Para encender, acerca una llama limpia sin tocar directamente el pie, gira la pieza y tuesta el borde de manera uniforme antes de la primera calada.", tags:["Corte","Encendido","Ritual"] },
  { number:"05", category:"Lectura sensorial", title:"Fuerza no es sabor", lead:"Intensidad, cuerpo y aroma describen dimensiones distintas.", body:"La fortaleza se relaciona con la sensación de nicotina; el cuerpo, con la densidad percibida; y el sabor, con las notas que aparecen durante la fumada. Un puro suave puede ser aromáticamente complejo y uno fuerte puede ser equilibrado.", tags:["Fortaleza","Cuerpo","Notas"] },
  { number:"06", category:"Cava", title:"Conservar el equilibrio", lead:"Temperatura y humedad estables protegen hoja, tiro y combustión.", body:"Perro Negro recomienda conservar sus piezas entre 16 y 18 °C y entre 65% y 75% de humedad relativa, preferentemente en madera. Los cambios bruscos y los conservantes artificiales no forman parte de este producto orgánico.", tags:["Humedad","Temperatura","Cuidado"] },
];

export default function Journal(){
  return <section className="journal" id="bitacora">
    <div className="journal-heading"><div><p className="section-number">Bitácora del fumador · 02</p><h2>Conocer la hoja<br/><em>cambia la fumada.</em></h2></div><p>Una guía para quien empieza y un lugar de consulta para quien ya reconoce el carácter de una buena pieza.</p></div>
    <div className="journal-grid">{articles.map((article)=><article key={article.number}><div className="journal-meta"><span>{article.number}</span><p>{article.category}</p></div><h3>{article.title}</h3><strong>{article.lead}</strong><p>{article.body}</p><div>{article.tags.map(tag=><small key={tag}>{tag}</small>)}</div></article>)}</div>
  </section>
}
