"use client";
import { useMemo, useState } from "react";

type Product={name:string;subtitle:string;profile:string;price:number;image:string;strength:string};
const basePath=process.env.NEXT_PUBLIC_BASE_PATH||"";
const asset=(path:string)=>`${basePath}${path}`;
const products:Product[]=[
{name:"Cachorro",subtitle:"Pequeño · Ascendente",profile:"Sabores cambiantes y una intensidad que crece con cada tercio.",price:14,strength:"Media",image:"/images/cachorro.svg"},
{name:"Faldero",subtitle:"Sutil · Casual",profile:"Una combinación serena de aromas y sabores moderados.",price:16,strength:"Suave",image:"/images/faldero.svg"},
{name:"Mestizo",subtitle:"Equilibrado · Noble",profile:"Una mezcla completa, armónica y fiel al tabaco negro ecuatoriano.",price:18,strength:"Media",image:"/images/mestizo.svg"},
{name:"Vagabundo",subtitle:"Pausado · Uniforme",profile:"Un recorrido sin prisa, de cepo ordenado y carácter constante.",price:19,strength:"Media",image:"/images/vagabundo.svg"},
{name:"Goloso",subtitle:"Corto · Gran calibre",profile:"Matices saturados y generosos en una fumada de corta distancia.",price:20,strength:"Alta",image:"/images/goloso.svg"},
{name:"Arisco",subtitle:"Intenso · Sorprendente",profile:"Presencia firme desde el encendido, con capas que se revelan en cada calada.",price:22,strength:"Alta",image:"/images/arisco.svg"}];

export default function Home(){
 const[ageOpen,setAgeOpen]=useState(true),[cartOpen,setCartOpen]=useState(false),[checkout,setCheckout]=useState(false),[filter,setFilter]=useState("Todos"),[cart,setCart]=useState<Record<string,number>>({}),[notice,setNotice]=useState("");
 const visible=filter==="Todos"?products:products.filter(p=>p.strength===filter),count=Object.values(cart).reduce((a,b)=>a+b,0),total=useMemo(()=>products.reduce((s,p)=>s+p.price*(cart[p.name]||0),0),[cart]);
 function add(name:string){setCart(c=>({...c,[name]:(c[name]||0)+1}));setNotice(`${name} se añadió a tu selección`);setTimeout(()=>setNotice(""),2200)}
 function update(name:string,delta:number){setCart(c=>({...c,[name]:Math.max(0,(c[name]||0)+delta)}))}
 return <main>
 {ageOpen&&<div className="age-gate" role="dialog" aria-modal="true"><div className="age-card"><div className="seal">PN</div><p className="eyebrow">Acceso responsable</p><h2>¿Eres mayor de 18 años?</h2><p>Este sitio presenta productos de tabaco destinados exclusivamente a personas adultas en Ecuador.</p><div className="age-actions"><button className="button primary" onClick={()=>setAgeOpen(false)}>Sí, soy mayor de 18</button><a className="button ghost" href="https://www.google.com">No, salir del sitio</a></div><small>El consumo de tabaco es nocivo para la salud.</small></div></div>}
 <header className="nav"><a className="brand" href="#inicio"><span className="brand-mark">PN</span><span>PERRO NEGRO<small>Tabaco ecuatoriano</small></span></a><nav><a href="#puros">La jauría</a><a href="#origen">Nuestro oficio</a><a href="#conservacion">Conservación</a></nav><button className="cart-button" onClick={()=>setCartOpen(true)}>Bolsa <span>{count}</span></button></header>
 <section className="hero" id="inicio" style={{backgroundImage:`url('${asset("/images/hero.svg")}')`}}><div className="hero-overlay"/><div className="hero-content"><p className="eyebrow">Hecho a mano en Ecuador</p><h1>El carácter de nuestra tierra, <em>en cada hoja.</em></h1><p className="hero-copy">Puros artesanales elaborados con tabaco negro ecuatoriano, paciencia y el oficio de maestras enrolladoras.</p><a className="button light" href="#puros">Conoce la jauría <span>↓</span></a></div><div className="hero-note"><span>01</span><p>Orgánico<br/>Natural<br/>Artesanal</p></div></section>
 <section className="intro" id="origen" style={{backgroundImage:`linear-gradient(90deg,#100b08e8,#23160dd4),url('${asset("/images/origin.svg")}')`}}><div className="workshop-label"><span>01</span><p>Nacido en<br/>la mitad<br/>del mundo</p></div><div className="intro-copy"><p className="section-number">Nuestro oficio</p><h2>De la tierra a las manos. <em>De las manos, al tiempo.</em></h2><p>Seleccionamos combinaciones idóneas entre las variedades que mejor se producen en Ecuador. Cada hoja atraviesa germinación, cosecha, secado, fermentación, selección y añejamiento antes de llegar a las manos de nuestras maestras enrolladoras.</p><div className="values"><span>Hoja entera</span><span>Trato justo</span><span>Proceso natural</span></div></div><div className="maker-stamp"><b>100%</b><span>Tabaco negro<br/>ecuatoriano</span></div></section>
 <section className="shop" id="puros" style={{backgroundImage:`linear-gradient(#20140dcf,#20140de8),url('${asset("/images/hero.svg")}')`}}><div className="shop-heading"><div><p className="section-number">Catálogo · 02</p><h2>Conoce a<br/><em>la jauría</em></h2><p className="shop-lead">Cada nombre es una actitud. Cada mezcla, un carácter.</p></div><div className="filters">{["Todos","Suave","Media","Alta"].map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><div className="product-grid">{visible.map((p,i)=><article className="product" key={p.name}><div className="product-image"><img src={asset(p.image)} alt={`Puro Perro Negro ${p.name}`} width="824" height="394" loading="lazy" decoding="async"/><span className="strength">Fuerza · {p.strength}</span><span className="product-index">P.N. / 0{i+1}</span></div><div className="cigar-band"><small>Hecho a mano · Ecuador</small><b>PERRO NEGRO</b></div><div className="product-info"><div><p>{p.subtitle}</p><h3>{p.name}</h3></div><strong>${p.price.toFixed(2)}</strong></div><p className="profile">{p.profile}</p><button className="add" onClick={()=>add(p.name)}>Sumar a mi selección <span>＋</span></button></article>)}</div><p className="price-note">Precios referenciales para esta primera versión visual; se actualizarán con el catálogo oficial.</p></section>
 <section className="quote" style={{backgroundImage:`linear-gradient(90deg,#090605e8,#120c08a6),url('${asset("/images/quote.svg")}')`}}><div className="quote-mark">P.N.</div><div><span>“</span><blockquote>Las sutiles variaciones de cada hoja son nuestra alquimia.</blockquote><p>— Fabricio Lalama · Maestro tabaquero</p></div></section>
 <section className="care" id="conservacion"><div className="care-image" style={{backgroundImage:`linear-gradient(#120d0877,#120d0877),url('${asset("/images/care.svg")}')`}}/><div className="care-content"><p className="section-number">03 — Conservar el ritual</p><h2>El tiempo también forma parte del sabor.</h2><p>Guarda tus puros entre <strong>16 y 18 °C</strong>, con una humedad relativa de <strong>65% a 75%</strong>. Una caja de madera ayuda a mantener el equilibrio natural, sin conservantes químicos.</p><a href="#puros">Elegir un puro <span>→</span></a></div></section>
 <footer><div className="brand footer-brand"><span className="brand-mark">PN</span><span>PERRO NEGRO<small>Quito · Ecuador</small></span></div><p>Tabaco ecuatoriano, hecho con oficio.</p><div><a href="#">Instagram</a><a href="#">Contacto</a><a href="#">Políticas</a></div><small>Venta exclusiva para mayores de 18 años. El consumo de tabaco es nocivo para la salud.</small></footer>
 {notice&&<div className="toast">✓ {notice}</div>}
 {cartOpen&&<><button className="scrim" onClick={()=>{setCartOpen(false);setCheckout(false)}}/><aside className="drawer"><div className="drawer-head"><div><p className="eyebrow">Tu selección</p><h2>{checkout?"Finalizar pedido":"La bolsa"}</h2></div><button onClick={()=>{setCartOpen(false);setCheckout(false)}}>×</button></div>{checkout?<Checkout total={total} onBack={()=>setCheckout(false)}/>:count===0?<div className="empty"><span>PN</span><h3>Tu bolsa está vacía</h3><p>Explora la jauría y encuentra el carácter que buscas.</p><button className="button primary" onClick={()=>setCartOpen(false)}>Ver puros</button></div>:<div className="cart-content"><div className="cart-lines">{products.filter(p=>cart[p.name]).map(p=><div className="cart-line" key={p.name}><img src={asset(p.image)} alt="" width="82" height="100" loading="lazy" decoding="async"/><div><h3>{p.name}</h3><p>${p.price.toFixed(2)}</p><div className="qty"><button onClick={()=>update(p.name,-1)}>−</button><span>{cart[p.name]}</span><button onClick={()=>update(p.name,1)}>＋</button></div></div><strong>${(p.price*cart[p.name]).toFixed(2)}</strong></div>)}</div><div className="summary"><div><span>Envío</span><span>Calculado al pagar</span></div><div className="total"><span>Total</span><strong>${total.toFixed(2)}</strong></div><button className="button primary wide" onClick={()=>setCheckout(true)}>Continuar al pago</button><small>Entrega únicamente dentro de Ecuador a personas mayores de 18 años.</small></div></div>}</aside></>}
 </main>
}

function Checkout({total,onBack}:{total:number;onBack:()=>void}){const[done,setDone]=useState(false);if(done)return <div className="success"><span>✓</span><h3>Tu pedido está listo para procesarse</h3><p>Esta demostración no realiza cargos reales. Al conectar la pasarela de pago, el cliente recibirá aquí su confirmación y número de pedido.</p><button className="button ghost" onClick={onBack}>Volver a la bolsa</button></div>;return <form className="checkout" onSubmit={e=>{e.preventDefault();setDone(true)}}><button type="button" className="back" onClick={onBack}>← Volver</button><label>Nombre completo<input required placeholder="Nombre y apellido"/></label><label>Cédula<input required inputMode="numeric" placeholder="0000000000"/></label><label>Correo electrónico<input required type="email" placeholder="correo@ejemplo.com"/></label><label>Ciudad<select required defaultValue=""><option value="" disabled>Selecciona tu ciudad</option><option>Quito</option><option>Guayaquil</option><option>Cuenca</option><option>Otra ciudad</option></select></label><label>Dirección de entrega<textarea required placeholder="Calle principal, número y referencia"/></label><div className="payment-placeholder"><span>Pago seguro</span><p>La pasarela ecuatoriana se conectará aquí. No se solicitan datos de tarjeta en esta demostración.</p></div><div className="total"><span>Total</span><strong>${total.toFixed(2)}</strong></div><label className="legal-check"><input type="checkbox" required/> Confirmo que soy mayor de 18 años y recibiré personalmente el pedido.</label><button className="button primary wide" type="submit">Simular confirmación</button></form>}
